//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Pages_AccountOwnership {
    
    /// <summary>
    /// upnlAccountProfile control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.UpdatePanel upnlAccountProfile;
    
    /// <summary>
    /// ucAccountSearchControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_AccountSearchControl ucAccountSearchControl;
    
    /// <summary>
    /// pnlMassUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlMassUpdate;
    
    /// <summary>
    /// SkyStemARTGridMassUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_SkyStemARTGrid SkyStemARTGridMassUpdate;
    
    /// <summary>
    /// lblAccountNumberMass control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblAccountNumberMass;
    
    /// <summary>
    /// lblAccountNameMass control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblAccountNameMass;
    
    /// <summary>
    /// lblNetAccountMass control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblNetAccountMass;
    
    /// <summary>
    /// lblPreparer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblPreparer;
    
    /// <summary>
    /// lblReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblReviewer;
    
    /// <summary>
    /// lblApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblApprover;
    
    /// <summary>
    /// lblBackupPreparer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBackupPreparer;
    
    /// <summary>
    /// lblBackupReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBackupReviewer;
    
    /// <summary>
    /// lblBackupApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBackupApprover;
    
    /// <summary>
    /// rowAttributeSetting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableRow rowAttributeSetting;
    
    /// <summary>
    /// lblAttribute control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblAttribute;
    
    /// <summary>
    /// ddlAccountAttribute control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ddlAccountAttribute;
    
    /// <summary>
    /// rfvAccountAttribute control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExRequiredFieldValidator rfvAccountAttribute;
    
    /// <summary>
    /// txtOwner control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox txtOwner;
    
    /// <summary>
    /// aceAssignedTo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.AutoCompleteExtender aceAssignedTo;
    
    /// <summary>
    /// pnlAccounts control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlAccounts;
    
    /// <summary>
    /// pnlGrid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlGrid;
    
    /// <summary>
    /// ucSkyStemARTGrid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_SkyStemARTGrid ucSkyStemARTGrid;
    
    /// <summary>
    /// lblAccountNumber control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblAccountNumber;
    
    /// <summary>
    /// lblAccountName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblAccountName;
    
    /// <summary>
    /// lblNetAccount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblNetAccount;
    
    /// <summary>
    /// ucPreparer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_UserDropDown ucPreparer;
    
    /// <summary>
    /// lblPreparerExport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblPreparerExport;
    
    /// <summary>
    /// ucReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_UserDropDown ucReviewer;
    
    /// <summary>
    /// vldComparePreparerAndReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator vldComparePreparerAndReviewer;
    
    /// <summary>
    /// lblReviewerExport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblReviewerExport;
    
    /// <summary>
    /// ucApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_UserDropDown ucApprover;
    
    /// <summary>
    /// vldComparePreparerAndApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator vldComparePreparerAndApprover;
    
    /// <summary>
    /// vldCompareApproverAndReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator vldCompareApproverAndReviewer;
    
    /// <summary>
    /// lblApproverExport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblApproverExport;
    
    /// <summary>
    /// ucBackupPreparer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_UserDropDown ucBackupPreparer;
    
    /// <summary>
    /// vldCompareBackupPreparer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator vldCompareBackupPreparer;
    
    /// <summary>
    /// lblBackupPreparerExport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBackupPreparerExport;
    
    /// <summary>
    /// ucBackupReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_UserDropDown ucBackupReviewer;
    
    /// <summary>
    /// vldCompareBackupReviewer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator vldCompareBackupReviewer;
    
    /// <summary>
    /// lblBackupReviewerExport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBackupReviewerExport;
    
    /// <summary>
    /// ucBackupApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_UserDropDown ucBackupApprover;
    
    /// <summary>
    /// vldCompareBackupApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator vldCompareBackupApprover;
    
    /// <summary>
    /// cvApproverBackupApprover control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CustomValidator cvApproverBackupApprover;
    
    /// <summary>
    /// lblBackupApproverExport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBackupApproverExport;
    
    /// <summary>
    /// chkExcludeOwnershipForZBA control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExCheckBox chkExcludeOwnershipForZBA;
    
    /// <summary>
    /// txtExcludeOwnershipValue control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputText txtExcludeOwnershipValue;
    
    /// <summary>
    /// btnSave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExButton btnSave;
    
    /// <summary>
    /// btnReset control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExButton btnReset;
    
    /// <summary>
    /// btnCancel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExButton btnCancel;
    
    /// <summary>
    /// hdnConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hdnConfirm;
    
    /// <summary>
    /// hdnOwner control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hdnOwner;
    
    /// <summary>
    /// hdnConfirm_BlankOwner control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hdnConfirm_BlankOwner;
    
    /// <summary>
    /// LegendOnAccountSearch control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_LegendOnAccountSearch LegendOnAccountSearch;
    
    /// <summary>
    /// ucAccountProfileMassAndBulkUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_ProgressBar ucAccountProfileMassAndBulkUpdate;
    
    /// <summary>
    /// Sel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputText Sel;
}
