//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Pages_DataImportStatus {
    
    /// <summary>
    /// upnlDataImportStatus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.UpdatePanel upnlDataImportStatus;
    
    /// <summary>
    /// pnlBusinessAdminDDL control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlBusinessAdminDDL;
    
    /// <summary>
    /// lblBusinessAdmin control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblBusinessAdmin;
    
    /// <summary>
    /// ddlBA control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ddlBA;
    
    /// <summary>
    /// pnlRecAndHolidayDataImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlRecAndHolidayDataImport;
    
    /// <summary>
    /// lblGridHeading control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblGridHeading;
    
    /// <summary>
    /// rgRecAndHolidayDataImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.TelerikWebControls.ExRadGrid rgRecAndHolidayDataImport;
    
    /// <summary>
    /// lblGridHeading2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblGridHeading2;
    
    /// <summary>
    /// pnlServiceDataImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlServiceDataImport;
    
    /// <summary>
    /// rgDataImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.TelerikWebControls.ExRadGrid rgDataImport;
    
    /// <summary>
    /// btnNewDataImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExButton btnNewDataImport;
    
    /// <summary>
    /// btnDeleteDataImport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExButton btnDeleteDataImport;
    
    /// <summary>
    /// lblHeading control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblHeading;
    
    /// <summary>
    /// imgSuccess control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExImage imgSuccess;
    
    /// <summary>
    /// ExLabel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel1;
    
    /// <summary>
    /// imgFailure control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExImage imgFailure;
    
    /// <summary>
    /// ExLabel2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel2;
    
    /// <summary>
    /// imgWarning control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExImage imgWarning;
    
    /// <summary>
    /// ExLabel3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel3;
    
    /// <summary>
    /// imgProcessing control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExImage imgProcessing;
    
    /// <summary>
    /// ExLabel4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel4;
    
    /// <summary>
    /// ExImage1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExImage ExImage1;
    
    /// <summary>
    /// ExLabel5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel5;
    
    /// <summary>
    /// ExImage2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExImage ExImage2;
    
    /// <summary>
    /// ExLabel6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel6;
    
    /// <summary>
    /// ucDataImportStatus control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_ProgressBar ucDataImportStatus;
    
    /// <summary>
    /// Sel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField Sel;
}
