//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Pages_PopupExchangeRates {
    
    /// <summary>
    /// lblRecPeriod control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblRecPeriod;
    
    /// <summary>
    /// rgExchangeRates control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.TelerikWebControls.ExRadGrid rgExchangeRates;
}
