//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class UserControls_ExchangeRateBar {
    
    /// <summary>
    /// Label1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel Label1;
    
    /// <summary>
    /// lblLCCYtoBCCYValue control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblLCCYtoBCCYValue;
    
    /// <summary>
    /// ExLabel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel ExLabel1;
    
    /// <summary>
    /// lblLCCYtoRCCYValue control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblLCCYtoRCCYValue;
}
