//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Pages_Matching_MatchingWizard {
    
    /// <summary>
    /// pnlMatchingWizard control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlMatchingWizard;
    
    /// <summary>
    /// wzMatching control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Wizard wzMatching;
    
    /// <summary>
    /// wzStepMatchingSourceSelection control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WizardStep wzStepMatchingSourceSelection;
    
    /// <summary>
    /// ucMatchingSourceSelection control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.Matching.Wizard.MatchingSourceSelection ucMatchingSourceSelection;
    
    /// <summary>
    /// wzStepMatchingSourceFilter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WizardStep wzStepMatchingSourceFilter;
    
    /// <summary>
    /// ucMatchingSourceFilter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.Matching.Wizard.MatchingSourceFilter ucMatchingSourceFilter;
    
    /// <summary>
    /// wzStepMatchingConfiguration control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WizardStep wzStepMatchingConfiguration;
    
    /// <summary>
    /// ucMatchingConfiguration control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.Matching.Wizard.MatchingConfiguration ucMatchingConfiguration;
    
    /// <summary>
    /// wzStepDisplayColumnSelection control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WizardStep wzStepDisplayColumnSelection;
    
    /// <summary>
    /// ucDisplayColumnSelection control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.Matching.Wizard.DisplayColumnSelection ucDisplayColumnSelection;
    
    /// <summary>
    /// wzStepRecItemColumnMapping control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WizardStep wzStepRecItemColumnMapping;
    
    /// <summary>
    /// ucRecItemColumnMapping control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.Matching.Wizard.RecItemColumnMapping ucRecItemColumnMapping;
    
    /// <summary>
    /// wzStepPreviewConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WizardStep wzStepPreviewConfirm;
    
    /// <summary>
    /// PreviewConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.Matching.Wizard.PreviewConfirm PreviewConfirm;
    
    /// <summary>
    /// btnBack control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExButton btnBack;
}
