//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Pages_Matching_ViewRecItems {
    
    /// <summary>
    /// pnlClosedItems control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlClosedItems;
    
    /// <summary>
    /// lblGridHeading2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.Library.Controls.WebControls.ExLabel lblGridHeading2;
    
    /// <summary>
    /// ucGLDataRecItemGrid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.UserControls_GLDataRecItemGrid ucGLDataRecItemGrid;
    
    /// <summary>
    /// ucGLDataRecurringScheduleItemsGrid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.UserControls_GLDataRecurringScheduleItemsGrid ucGLDataRecurringScheduleItemsGrid;
    
    /// <summary>
    /// ucGLDataWriteOnOffGrid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::SkyStem.ART.Web.UserControls.UserControls_GLDataWriteOnOffGrid ucGLDataWriteOnOffGrid;
}
