//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyStem.ART.Web.UserControls {
    
    
    public partial class DocumentUploadButton {
        
        /// <summary>
        /// imgbtnDocument control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyStem.Library.Controls.WebControls.ExImageButton imgbtnDocument;
        
        /// <summary>
        /// RadWindowOpenDocument control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadWindow RadWindowOpenDocument;
    }
}
